openapi: 3.0.3
info:
  title: Multi-party timestamping server
  version: 0.0.0
tags:
  - name: stamp
    description: Perform document timestamping
paths:
  /sign/2:
    post:
      tags:
        - stamp
      summary: Signs a new document
      operationId: sign
      requestBody:
        description: Request for a new timestamp
        content:
          text/plain:
            schema:
              description: "Data in format: other_party_id,other_party_address,data_to_sign,unix_seconds_timestamp"
              type: string
        required: true
      responses:
        '200':
          description: Successful signature
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/TimestampResponse'
        '405':
          description: Invalid input
        '502':
          description: Not enough servers participated in time
  /verify:
    post:
      tags:
        - stamp
      summary: Verifies an existing document stamp
      operationId: verify
      requestBody:
        description: Tries to verify existing timestamp
        content:
          text/plain:
            schema:
              description: "Data in format: signature_output;signed_data;unix_seconds_timestamp"
              type: string
        required: true
      responses:
        '202':
          description: Successful operation
          content:
            text/plain:
              schema:
                description: True if successfully verified, false if not
                type: boolean
        '405':
          description: Invalid input
        '502':
          description: Not enough servers participated in time

components:
  schemas:
    TimestampResponse:
      type: string
      format: binary
      description: Binary timestamp file
